version: "3"
 
services:
  beike-chart:
    build: 
      context: .
      dockerfile: ./dockerfile
    image: beike-chart
    container_name: beike-chart
    networks:
      default:
        ipv4_address: 172.18.0.6
    restart: always
    environment:
      TZ: Asia/Shanghai

networks:
  default:
    external: true
    name: baobao_blog_my-net
